language: rust
cache: cargo
env:
  - ROSRUST_MSG_PATH=/home/travis/build/adnanademovic/rosrust/rosrust_codegen/src/msg_examples
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
