language: rust
env:
  - ROSRUST_MSG_PATH=/home/travis/build/adnanademovic/rosrust/rosrust/src/build_tools/msg_examples
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
