[package]
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Pure Rust implementation of a ROS client library"
license = "MIT"
name = "rosrust"
readme = "README.md"
repository = "https://github.com/adnanademovic/rosrust"
version = "0.4.0"

[dependencies]
byteorder = "0.5"
error-chain = "0.7"
lazy_static = "0.2"
log = "0.3"
nix = "0.7"
regex = "0.1"
rustc-serialize = "0.3"
xml-rs = "0.3"

[dependencies.hyper]
default-features = false
version = "0.9"
