[package]
name = "rosrust"
version = "0.3.0"
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Pure Rust implementation of a ROS client library"
license = "MIT"
repository = "https://github.com/adnanademovic/rosrust"
readme = "README.md"

[dependencies]
byteorder = "0.5"
rustc-serialize = "0.3"
xml-rs = "0.3"
nix = "0.7"
regex = "0.1"
lazy_static = "0.2"

[dependencies.hyper]
version = "0.9"
default-features = false
