[package]
name = "rosrust"
version = "0.0.1"
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Pure Rust implementation of ROS client library"
license = "MIT"
repository = "https://github.com/adnanademovic/rosrust"
readme = "README.md"

[dependencies]
