[package]
authors = ["Adnan Ademovic <adnanademovic100@gmail.com>"]
description = "Message generation for rosrust"
license = "MIT"
name = "rosrust_codegen"
readme = "../README.md"
repository = "https://github.com/adnanademovic/rosrust"
version = "0.6.5"

[dependencies]
error-chain = "0.11.0"
lazy_static = "1.0.0"
regex = "0.2.3"
rust-crypto = "0.2.36"
quote = "0.6.2"
syn = "0.14.0"
proc-macro2 = "0.4.3"

[lib]
proc-macro = true
